"""initial schema

Revision ID: 06feedab4c00
Revises: 
Create Date: 2026-07-28 17:47:13.386130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06feedab4c00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_data_log',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('keystrokes', sa.Integer(), nullable=True),
    sa.Column('mouse_distance', sa.Integer(), nullable=True),
    sa.Column('active_window', sa.String(), nullable=True),
    sa.Column('focus_score', sa.Integer(), nullable=True),
    sa.Column('workload_score', sa.Integer(), nullable=True),
    sa.Column('cognitive_load', sa.Integer(), nullable=True),
    sa.Column('mental_state', sa.String(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('project_id', 'timestamp')
    )
    op.create_table('activity_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('focus_score', sa.Float(), nullable=True),
    sa.Column('cognitive_load', sa.Float(), nullable=True),
    sa.Column('keystrokes', sa.Integer(), nullable=True),
    sa.Column('mouse_distance', sa.Float(), nullable=True),
    sa.Column('context_switches', sa.Integer(), nullable=True),
    sa.Column('deep_work_minutes', sa.Float(), nullable=True),
    sa.Column('recovery_minutes', sa.Float(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('feature_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_feature_id'), 'activity_feature', ['id'], unique=False)
    op.create_index(op.f('ix_activity_feature_timestamp'), 'activity_feature', ['timestamp'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_date'), 'journal_entries', ['date'], unique=False)
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smart_breaks', sa.Boolean(), nullable=True),
    sa.Column('comparative_mode', sa.Boolean(), nullable=True),
    sa.Column('reflection_journal', sa.Boolean(), nullable=True),
    sa.Column('passive_mode', sa.Boolean(), nullable=True),
    sa.Column('alert_burnout', sa.Boolean(), nullable=True),
    sa.Column('alert_focus_drop', sa.Boolean(), nullable=True),
    sa.Column('alert_context_switching', sa.Boolean(), nullable=True),
    sa.Column('alert_prolonged_work', sa.Boolean(), nullable=True),
    sa.Column('alert_sensitivity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploaded_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_activities_id'), 'uploaded_activities', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('keystrokes', sa.Integer(), nullable=True),
    sa.Column('mouse_distance', sa.Float(), nullable=True),
    sa.Column('active_window', sa.String(), nullable=True),
    sa.Column('focus_score', sa.Integer(), nullable=True),
    sa.Column('workload_score', sa.Integer(), nullable=True),
    sa.Column('cognitive_load', sa.Integer(), nullable=True),
    sa.Column('mental_state', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_activity_logs_timestamp'), 'activity_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_logs_timestamp'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_uploaded_activities_id'), table_name='uploaded_activities')
    op.drop_table('uploaded_activities')
    op.drop_table('settings')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_date'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_activity_feature_timestamp'), table_name='activity_feature')
    op.drop_index(op.f('ix_activity_feature_id'), table_name='activity_feature')
    op.drop_table('activity_feature')
    op.drop_table('activity_data_log')
    # ### end Alembic commands ###
